---

- name: Allow IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present

- name: Allow SELinux enabled systems to listen on any port
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true
  when:
    - ansible_selinux is defined
    - ansible_selinux['status'] == 'enabled'

- name: Create configuration from template
  ansible.builtin.template:
    src: "{{ haproxy_template }}"
    dest: "{{ haproxy_config_file }}"
    mode: "0644"
    group: root
    owner: root
    backup: "{{ haproxy_config_backup | bool }}"
  notify: Reload haproxy

- name: Start services
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Open firewall ports
  ansible.builtin.include_role:
    name: deitkrachten.firewall
  vars:
    firewall_ports: "{{ haproxy_firewall_ports }}"
